version: "3"
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      DB_ADMIN_PASS: root
      MYSQL_DATABASE: bank-sys
    ports:
      - "3306:3306"
