spring:
  application:
    name: AccountService
  datasource:
    platform: mariadb
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank-sys?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
